version: '3.7'

services:
  gitlab-runner: 
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ["H:\Development\Workspace IntelliJ\lean-tubecentric-docker\gitlab-runner\config"]:/etc/gitlab-runner
